### ISSUE TITLE
Few command/functions not working

### ISSUE THREAD

**Issue by TheBugHunterX** [bishalqx980/tgbot#20]
1. /webshot
- `Oops, something went wrong...`
2. /ytdl
- `Exception while accessing title of https://youtube.com/watch?v=KZGWfHdfWQs. Please file a bug report at https://github.com/pytube/pytube`
3. /itl
- `Oops, something went wrong...`

**Comment by bishalqx980** [comment]
Fixed ✅
3. /itl command

Need to be fix 
1. /webshot
2. /ytdl

**Comment by bishalqx980** [comment]
**🔰 Note (14/12/2024):** Certain features have been temporarily removed due to limitations. They may be reintroduced in future updates. Additionally, not all features are listed here. We encourage you to start the bot and explore its full functionality. Thank you for your understanding.
